load data
CHARACTERSET UTF8
INFILE './PMS_FOLIO.csv'
BADFILE './PMS_FOLIO_MAPP.txt_par.bad'
DISCARDFILE './PMS_FOLIO_MAPP.txt_par.dsc'
Append
INTO TABLE migadm.PMS_FOLIO_MAPP
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
(
PAN_NUMBER ,
FOLIO_NUMBER ,
SCHEME_CODE	   ,
CUSTOMER_NAME ,
CUSTOMER_ID	,
ISSUER_ID	 ,
OPERATION	 ,
ASSET_CLASS	 ,
INVESTMENT_ID  )   
